# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Photobook CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - name: Set up SSH
        run: |
          set -eu
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "${{secrets.KEY}}" > "$SSH_PATH/key"
          chmod 700 "$SSH_PATH" && chmod 600 "$SSH_PATH/key"
          ssh-keyscan github.com >> $SSH_PATH/known_hosts
      # Build
      # - run: npm ci
      #- run: npm run build:all
      #- run: npm test
      # Deploy
      - name: Install PM2
        run: npm i pm2 -g

      - name: Deploy
        run: |
          echo "PM2 run setup"
          TARGET_SERVER_HOST=${{secrets.TARGET_SERVER_HOST}} TARGET_SERVER_USER=${{secrets.TARGET_SERVER_USER}} pm2 deploy ecosystem.config.js production setup 2>&1 || true
          echo "PM2 run deploy"
          PGPASSWORD=${{secrets.PGPASSWORD}} TARGET_SERVER_HOST=${{secrets.TARGET_SERVER_HOST}} TARGET_SERVER_USER=${{secrets.TARGET_SERVER_USER}} pm2 deploy ecosystem.config.js production
